apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcast-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broadcast
  template:
    metadata:
      labels:
        app: broadcast
    spec:
      containers:
        - name: broadcast-service
          image: broadcast-service:latest
          env:
            - name: RECEIVER_SERVICE_URL
              value: "http://receiver-service:5002"
          imagePullPolicy: IfNotPresent
