apiVersion: apps/v1
kind: Deployment
metadata:
  name: receiver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: receiver
  template:
    metadata:
      labels:
        app: receiver
    spec:
      containers:
        - name: receiver-service
          image: receiver-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5002
